/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuditRouteImport } from './routes/audit'
import { Route as DocumentsRouteImport } from './routes/documents'
import { Route as IntegrationsRouteImport } from './routes/integrations'
import { Route as OcrRouteImport } from './routes/ocr'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as ReportingRouteImport } from './routes/reporting'
import { Route as RetentionRouteImport } from './routes/retention'
import { Route as SearchRouteImport } from './routes/search'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SharingRouteImport } from './routes/sharing'
import { Route as SignatureRouteImport } from './routes/signature'
import { Route as VersionsRouteImport } from './routes/versions'
import { Route as WorkflowsRouteImport } from './routes/workflows'
import { Route as WorkspacesRouteImport } from './routes/workspaces'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditRoute = AuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsRoute = DocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrationsRoute = IntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => rootRouteImport,
} as any)
const OcrRoute = OcrRouteImport.update({
  id: '/ocr',
  path: '/ocr',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportingRoute = ReportingRouteImport.update({
  id: '/reporting',
  path: '/reporting',
  getParentRoute: () => rootRouteImport,
} as any)
const RetentionRoute = RetentionRouteImport.update({
  id: '/retention',
  path: '/retention',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SharingRoute = SharingRouteImport.update({
  id: '/sharing',
  path: '/sharing',
  getParentRoute: () => rootRouteImport,
} as any)
const SignatureRoute = SignatureRouteImport.update({
  id: '/signature',
  path: '/signature',
  getParentRoute: () => rootRouteImport,
} as any)
const VersionsRoute = VersionsRouteImport.update({
  id: '/versions',
  path: '/versions',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkflowsRoute = WorkflowsRouteImport.update({
  id: '/workflows',
  path: '/workflows',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspacesRoute = WorkspacesRouteImport.update({
  id: '/workspaces',
  path: '/workspaces',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/audit': typeof AuditRoute
  '/documents': typeof DocumentsRoute
  '/integrations': typeof IntegrationsRoute
  '/ocr': typeof OcrRoute
  '/portal': typeof PortalRoute
  '/reporting': typeof ReportingRoute
  '/retention': typeof RetentionRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/sharing': typeof SharingRoute
  '/signature': typeof SignatureRoute
  '/versions': typeof VersionsRoute
  '/workflows': typeof WorkflowsRoute
  '/workspaces': typeof WorkspacesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/audit': typeof AuditRoute
  '/documents': typeof DocumentsRoute
  '/integrations': typeof IntegrationsRoute
  '/ocr': typeof OcrRoute
  '/portal': typeof PortalRoute
  '/reporting': typeof ReportingRoute
  '/retention': typeof RetentionRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/sharing': typeof SharingRoute
  '/signature': typeof SignatureRoute
  '/versions': typeof VersionsRoute
  '/workflows': typeof WorkflowsRoute
  '/workspaces': typeof WorkspacesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/audit': typeof AuditRoute
  '/documents': typeof DocumentsRoute
  '/integrations': typeof IntegrationsRoute
  '/ocr': typeof OcrRoute
  '/portal': typeof PortalRoute
  '/reporting': typeof ReportingRoute
  '/retention': typeof RetentionRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/sharing': typeof SharingRoute
  '/signature': typeof SignatureRoute
  '/versions': typeof VersionsRoute
  '/workflows': typeof WorkflowsRoute
  '/workspaces': typeof WorkspacesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/audit'
    | '/documents'
    | '/integrations'
    | '/ocr'
    | '/portal'
    | '/reporting'
    | '/retention'
    | '/search'
    | '/settings'
    | '/sharing'
    | '/signature'
    | '/versions'
    | '/workflows'
    | '/workspaces'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/audit'
    | '/documents'
    | '/integrations'
    | '/ocr'
    | '/portal'
    | '/reporting'
    | '/retention'
    | '/search'
    | '/settings'
    | '/sharing'
    | '/signature'
    | '/versions'
    | '/workflows'
    | '/workspaces'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/audit'
    | '/documents'
    | '/integrations'
    | '/ocr'
    | '/portal'
    | '/reporting'
    | '/retention'
    | '/search'
    | '/settings'
    | '/sharing'
    | '/signature'
    | '/versions'
    | '/workflows'
    | '/workspaces'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AuditRoute: typeof AuditRoute
  DocumentsRoute: typeof DocumentsRoute
  IntegrationsRoute: typeof IntegrationsRoute
  OcrRoute: typeof OcrRoute
  PortalRoute: typeof PortalRoute
  ReportingRoute: typeof ReportingRoute
  RetentionRoute: typeof RetentionRoute
  SearchRoute: typeof SearchRoute
  SettingsRoute: typeof SettingsRoute
  SharingRoute: typeof SharingRoute
  SignatureRoute: typeof SignatureRoute
  VersionsRoute: typeof VersionsRoute
  WorkflowsRoute: typeof WorkflowsRoute
  WorkspacesRoute: typeof WorkspacesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit': {
      id: '/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents': {
      id: '/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof DocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integrations': {
      id: '/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof IntegrationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ocr': {
      id: '/ocr'
      path: '/ocr'
      fullPath: '/ocr'
      preLoaderRoute: typeof OcrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reporting': {
      id: '/reporting'
      path: '/reporting'
      fullPath: '/reporting'
      preLoaderRoute: typeof ReportingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/retention': {
      id: '/retention'
      path: '/retention'
      fullPath: '/retention'
      preLoaderRoute: typeof RetentionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sharing': {
      id: '/sharing'
      path: '/sharing'
      fullPath: '/sharing'
      preLoaderRoute: typeof SharingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signature': {
      id: '/signature'
      path: '/signature'
      fullPath: '/signature'
      preLoaderRoute: typeof SignatureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/versions': {
      id: '/versions'
      path: '/versions'
      fullPath: '/versions'
      preLoaderRoute: typeof VersionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workflows': {
      id: '/workflows'
      path: '/workflows'
      fullPath: '/workflows'
      preLoaderRoute: typeof WorkflowsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspaces': {
      id: '/workspaces'
      path: '/workspaces'
      fullPath: '/workspaces'
      preLoaderRoute: typeof WorkspacesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AuditRoute: AuditRoute,
  DocumentsRoute: DocumentsRoute,
  IntegrationsRoute: IntegrationsRoute,
  OcrRoute: OcrRoute,
  PortalRoute: PortalRoute,
  ReportingRoute: ReportingRoute,
  RetentionRoute: RetentionRoute,
  SearchRoute: SearchRoute,
  SettingsRoute: SettingsRoute,
  SharingRoute: SharingRoute,
  SignatureRoute: SignatureRoute,
  VersionsRoute: VersionsRoute,
  WorkflowsRoute: WorkflowsRoute,
  WorkspacesRoute: WorkspacesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
